name: we_help_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.17
  cupertino_icons: ^1.0.2
  easy_debounce: ^2.0.2+1
  equatable: ^2.0.3
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.4.0+1
  formz: ^0.4.1
  get: ^4.6.1
  google_fonts: ^2.3.2
  oktoast: ^3.1.5

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
